# Generated by Django 4.0.3 on 2022-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='location',
            field=models.CharField(default='enter location', max_length=30),
        ),
        migrations.AddField(
            model_name='newuser',
            name='mobile',
            field=models.CharField(default='enter mobile', max_length=30),
        ),
    ]
