# Generated by Django 4.0.3 on 2022-03-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newuser_location_newuser_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
