# Generated by Django 4.0.3 on 2022-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
